### ISSUE TITLE
widget on constant 'load'

### ISSUE THREAD

**Issue by dvega3** [campaignzero/campaign-zero-widget#18]
#### Overview:

Widget is not working

#### Acceptance Criteria:

_( issue will not be considered complete unless this list of criteria is met, e.g. intended usage, expected functionality, specific metrics met, etc. )_

#### Steps to Duplicate _( required for bug reports )_:

added to my own site, not working there either. 

#### System Info _( required for bug reports )_:

Any platforms

#### Relevant Documentation _( optional )_

try it, not even the demo is working

**Comment by manifestinteractive** [comment]
Thanks for report this.  This was actually an issue with OpenStates.org rejecting our API Key since we had exceeded our threshold, which was more than double what we normally use in a day.  They have been gracious enough to remove the cap that was placed on our API Key, and we are now fully back in business.
