### ISSUE TITLE
Streamline asset loading for faster widget loading

### ISSUE THREAD

**Issue by jgaskins** [campaignzero/campaign-zero-widget#3]
Saw a tweet that the widget goes a bit slow under load. Several of the replies have mentioned server-side caching and that'll surely help, but I was wondering about streamlining the front end, as well.

Including the widget, 3 assets are requested from the server (app.js, CSS) as well as Google Analytics and (potentially) jQuery. It looks like the widget waits on GA to finish loading before it initializes — probably to be be able to track the load for it.

Here are some ideas I've got to improve it:
- Load styles within the widget source (that is, add a `<style>` tag to the DOM during execution)
- Load the app itself in the widget source
- Remove jQuery dependency if possible (`app.js` only uses it in two places)

This would consolidate everything into a single script, but would likely require either everything being shoved into a single script or adding a JS build step. Either way, it would streamline front-end loading performance a _lot_ and would remove the need to wait on GA to load before initializing the widget.

A friend and I would like to pair on this over the weekend, but just posting it here for discussion.

**Comment by laurendorman** [comment]
Great recommendations, @jgaskins – would love to see this happen.

**Comment by manifestinteractive** [comment]
I am looking into the speed issues now.  Currently we want GA to load before everything else so we can actually track widget usage.  While it is a free tool, it is important to know how people are using it so we can make improvements in these early stags.

In regards to the other assets, literally everything else is loaded asynchronously, so there should not be any load related issues with the static assets.  Especially since these assets are loaded over CDN's.  The only actual items we have in our stack that could slow down the widgets response time would be the interaction from the widget to the server that makes the API calls.  This is where I will be spending my initial focus to see what is happening there.

**Comment by latazzajones** [comment]
Nice. I'd also been thinking that the API call to Sunlight could be causing an issue. Not sure what else is in there.

**Comment by manifestinteractive** [comment]
So, the issue was the external API calls were maxing out the CPU.  The caching of the API calls was the right way to go, unfortunately the last PR actually broke the widget.  It was certainly the right direction to go though, so thanks @jonathanstegall !!!

You can see the drastic difference caching the API made to our CPU.

![screen shot 2016-07-07 at 2 22 04 pm](https://cloud.githubusercontent.com/assets/508411/16664581/ad61b584-444e-11e6-895f-dff717595f0f.png)

**Comment by jonathanstegall** [comment]
@manifestinteractive wonderful. I knew what the issue was; just clearly over my head on Digital Ocean. Is it all running well now?

**Comment by jonathanstegall** [comment]
@manifestinteractive also I'd still say remove that config.php if there's a way to keep it in Digital Ocean safely, so the API key is not publicly viewable in GitHub.

**Comment by manifestinteractive** [comment]
@jonathanstegall That is actually already the case.  The `config.php` file is actually ignored in github.  If you look in the source code, it is not there.  You have to copy the `config.dist.php` file ( which does NOT contain private data ).  This allows each installation of the widget to have their own private settings without being able to commit that code to the github repo.

In regards to the cache, I did have to make some modifications to it, as the cached files were not being ignored by github.  I created a new `./cache` folder and added a `.gitignore` file to ignore everything inside of it.  This will prevent corruption of the github repo by cached files that don't need to be there.

Also, the issue with the first caching attempts was that there was a `$args` param being passed into the cache method that was never actually defined, so it was causing the API calls to fail as the actual URL params were never being sent.  In addition, the `$filename` that was being used technically cached the same results for different params.  What I did was use an MD5 hash of the entire url with params as the file name.  That way every unique query could be cached for 24 hours.

Now the remaining issue to knock out is the network requests.  The widget is averaging about 1,000 PER SECOND ( see attached screen shot of real time users )  !!!  Which is basically creating a denial of service attack on our one small server just in network requests.  Meaning that it has nothing to do with the widget static assets or the PHP code, it is just the server trying to process the crap ton of requests coming in.  So the main index.html file is not even getting returned to load the widget to begin with as it is taking 10-30 seconds to return a response due to network queues.  I am currently looking into ways to help with network throttling so we can handle more traffic.  This widget is not very CPU / Memory intensive ( ~5% resources consumed ).  So literally the only thing left to solve is network throughput.

![screen shot 2016-07-07 at 4 43 19 pm](https://cloud.githubusercontent.com/assets/508411/16669186/25e858ce-4462-11e6-95ff-2ad69951174d.png)

![screen shot 2016-07-07 at 4 48 12 pm](https://cloud.githubusercontent.com/assets/508411/16669292/ae2a83ce-4462-11e6-880a-952b18138cb4.png)

**Comment by jonathanstegall** [comment]
@manifestinteractive I think you'll see there was a manually created version of config.php in a hurry because the original one got overwritten. Maybe will need a different API key long term.

**Comment by manifestinteractive** [comment]
well that just sucks :)  Ya, now that's apart of the permanent repo.  I am trashing it from this repo as it was never intended to be apart of it.  In the future, let's not add private details to the repo.

**Comment by manifestinteractive** [comment]
Alright, closing out this ticket.  We have the issue resolved now.  

Switched to HTTP2 for Apace2 and that resolved load issues.  HTTP1 network throttling is basically like lanes in a highway, only so many lanes and once you start getting a crap ton or cars, it fails to scale well for everyone trying to drive on the roads.

HTTP2 gives us WAY more lanes, and also has some smarter handling for routing people into lanes that are less busy.
